---
- hosts: all
  tasks:

  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present

  - name: Install Sql Server 2019
    win_chocolatey:
      name:
      - sql-server-2019
      state: present
