---
- hosts: all
  tasks:

  - name: set PowerShell memory allowance to 2GB
    win_shell: set-item wsman:localhost\Shell\MaxMemoryPerShellMB 2048
    
  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present
      
  - name: turn UAC off
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
      name: EnableLUA
      data: 0
      type: dword
      state: present
    register: uac_result

  - name: reboot after disabling UAC
    win_reboot:
    when: uac_result is changed 
    
  - name: Install Sql Server 2019
    win_chocolatey:
      name:
      - sql-server-2019
      state: present
    retries: 2
    delay: 3
    register: result
    until: result is succeeded    
