---
- hosts: all
  tasks:

  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present

  - name: Install google chrome
    win_chocolatey:
      name:
      - googlechrome
      state: present
  - name: Install adobe reader
    win_chocolatey:
      name:
      - adobereader
      state: present
  - name: Install vscode
    win_chocolatey:
      name:
      - vscode.install
      state: present
  - name: Install powershell
    win_chocolatey:
      name:
      - powershell-preview
      state: present
  - name: Install sql-server-management-studio
    win_chocolatey:
      name:
      - sql-server-management-studio
      state: present         
