---
- hosts: all
  tasks:

  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present
  - name: Reboot a machine that takes time to settle after being booted
    ansible.windows.win_reboot:
      post_reboot_delay: 120
  - name: Install Sql Server 2019
    win_chocolatey:
      name:
      - sql-server-2019
      state: present
    retries: 2
    delay: 3
    register: result
    until: result is succeeded    
