---
- hosts: all
  tasks:

  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present

  - name: Install VS Code and PowerShell Preview
    win_chocolatey:
      name:
      - googlechrome
      - adobereader
      - vscode.install
      - powershell-preview
      - sql-server-management-studio
      - sql-server-2019
      state: present
