---
- hosts: all
  tasks:

  - name: set PowerShell memory allowance to 2GB
    win_shell: set-item wsman:localhost\Shell\MaxMemoryPerShellMB 2048
  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present
  - name: Reboot a machine that takes time to settle after being booted
    win_reboot:
      post_reboot_delay: 120
  - name: Install Sql Server 2019
    win_chocolatey:
      name:
      - sql-server-2019 -y
      state: present
    retries: 2
    delay: 3
    register: result
    until: result is succeeded    
